// Generated by gencpp from file rss2_msgsrv_pkg/date_cmd_vel.msg
// DO NOT EDIT!


#ifndef RSS2_MSGSRV_PKG_MESSAGE_DATE_CMD_VEL_H
#define RSS2_MSGSRV_PKG_MESSAGE_DATE_CMD_VEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace rss2_msgsrv_pkg
{
template <class ContainerAllocator>
struct date_cmd_vel_
{
  typedef date_cmd_vel_<ContainerAllocator> Type;

  date_cmd_vel_()
    : pw_date()
    , pw_cmd_vel()  {
    }
  date_cmd_vel_(const ContainerAllocator& _alloc)
    : pw_date(_alloc)
    , pw_cmd_vel(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _pw_date_type;
  _pw_date_type pw_date;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _pw_cmd_vel_type;
  _pw_cmd_vel_type pw_cmd_vel;





  typedef boost::shared_ptr< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> const> ConstPtr;

}; // struct date_cmd_vel_

typedef ::rss2_msgsrv_pkg::date_cmd_vel_<std::allocator<void> > date_cmd_vel;

typedef boost::shared_ptr< ::rss2_msgsrv_pkg::date_cmd_vel > date_cmd_velPtr;
typedef boost::shared_ptr< ::rss2_msgsrv_pkg::date_cmd_vel const> date_cmd_velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator1> & lhs, const ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator2> & rhs)
{
  return lhs.pw_date == rhs.pw_date &&
    lhs.pw_cmd_vel == rhs.pw_cmd_vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator1> & lhs, const ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rss2_msgsrv_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63f9a130ea4a5bfb02bbb1541b739e89";
  }

  static const char* value(const ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63f9a130ea4a5bfbULL;
  static const uint64_t static_value2 = 0x02bbb1541b739e89ULL;
};

template<class ContainerAllocator>
struct DataType< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rss2_msgsrv_pkg/date_cmd_vel";
  }

  static const char* value(const ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pw_date\n"
"geometry_msgs/Twist pw_cmd_vel\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pw_date);
      stream.next(m.pw_cmd_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct date_cmd_vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rss2_msgsrv_pkg::date_cmd_vel_<ContainerAllocator>& v)
  {
    s << indent << "pw_date: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.pw_date);
    s << indent << "pw_cmd_vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.pw_cmd_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSS2_MSGSRV_PKG_MESSAGE_DATE_CMD_VEL_H
